require 'rubygems'
require 'rake'

require 'jeweler'
Jeweler::Tasks.new do |gem|
  # gem is a Gem::Specification... see http://docs.rubygems.org/read/chapter/20 for more options
  gem.name = "duostack"
  gem.version = `bin/duostack version`.chomp
  gem.summary = %Q{Duostack command line client}
  gem.description = %Q{Duostack command line client: create and manage Duostack apps}
  gem.homepage = "http://www.duostack.com/"
  gem.email = "todd@toddeichel.com"
  gem.authors = "Todd Eichel"
  gem.require_paths = ['.'] # default is ["lib"] but we don't have that
  
  gem.executables = ["duostack", ".duostack-expect", ".duostack-console-expect"]
end
